version: '3.4'


services: 
    api:
        hostname: 'api.electrocorp.com'
        build: './api/'
        links:
            - 'database'

        volumes:
            - './api/code:/usr/src/app:rw'

        networks:
            api_net:
                ipv4_address: 172.22.2.5

            database_net:
                ipv4_address: 172.22.4.2

        environment:
            SECRET_SALT: ^&?cY,t}pE>6rQu]$C#pRK^dns3B((}.e~*BzSgb5d7h*F;&FB/jD(>N\NSMX.b
            DATABASE_URL: postgresql://leader:mysecretpassword@172.22.4.5:5432/electrocorp
            FLASK_DEBUG: 1
        
        ports: 
            - '8555:80'
    
    admin:
        hostname: 'admin.electrocorp.com'
        build: './admin/'
        volumes:
            - './admin/code:/usr/src/app:ro'
        
        links:
            - 'api'
        
        networks:
            admin_net:
              ipv4_address: 172.22.3.5

    www:
        hostname: 'electrocorp.com'
        build: './www/'
        volumes: 
            - './www/code:/usr/src/app:rw'

        links:
            - 'api'

        networks:
            www_net:
              ipv4_address: 172.22.1.5
        
        environment: 
            FLASK_APP: run.py
            
    database:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: electrocorp
            POSTGRES_USER: leader

        volumes: 
            - psql_database:/var/lib/postgresql/data

        networks:
            database_net:
              ipv4_address: 172.22.4.5

    # mail:
    #     hostname: 'mail.electrocorp.com'
    #     build: ./mail/
    #     volumes: 
    #         - mail:/var/mail
        
    #     networks: 
    #         mail_net:
    #             ipv4_address: 172.22.5.5

          

volumes: 
    psql_database:
    mail:



networks:
    www_net:
        external:
            name: www
                
    api_net:
        external:
            name: api

    admin_net:
        external:
            name: admin

    database_net:
        external:
            name: database
    
    mail_net:
        external:
            name: mail
